title: /home/wenpin/site
author: wenpin
email: wpchou @at outlook
description: >
  technical
github_username:  wpchou
show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal


defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: [untag]


plugins:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 2
paginate_path: "page:num"
